name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore Forum/Forum.csproj --configfile Nuget.Config
    - name: Build
      run: dotnet build Forum/Forum.csproj --no-restore
    - name: Test
      run: dotnet test tests/ --no-build --verbosity normal
